// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: fibonacci.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type N struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N) Reset() {
	*x = N{}
	mi := &file_fibonacci_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N) ProtoMessage() {}

func (x *N) ProtoReflect() protoreflect.Message {
	mi := &file_fibonacci_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N.ProtoReflect.Descriptor instead.
func (*N) Descriptor() ([]byte, []int) {
	return file_fibonacci_proto_rawDescGZIP(), []int{0}
}

func (x *N) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type V struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             int64                  `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V) Reset() {
	*x = V{}
	mi := &file_fibonacci_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V) ProtoMessage() {}

func (x *V) ProtoReflect() protoreflect.Message {
	mi := &file_fibonacci_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V.ProtoReflect.Descriptor instead.
func (*V) Descriptor() ([]byte, []int) {
	return file_fibonacci_proto_rawDescGZIP(), []int{1}
}

func (x *V) GetV() int64 {
	if x != nil {
		return x.V
	}
	return 0
}

var File_fibonacci_proto protoreflect.FileDescriptor

const file_fibonacci_proto_rawDesc = "" +
	"\n" +
	"\x0ffibonacci.proto\"\x11\n" +
	"\x01N\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\"\x11\n" +
	"\x01V\x12\f\n" +
	"\x01v\x18\x01 \x01(\x03R\x01v2\x15\n" +
	"\x04Calc\x12\r\n" +
	"\x03fib\x12\x02.N\x1a\x02.VB\x0fZ\rfibexemplo/pbb\x06proto3"

var (
	file_fibonacci_proto_rawDescOnce sync.Once
	file_fibonacci_proto_rawDescData []byte
)

func file_fibonacci_proto_rawDescGZIP() []byte {
	file_fibonacci_proto_rawDescOnce.Do(func() {
		file_fibonacci_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fibonacci_proto_rawDesc), len(file_fibonacci_proto_rawDesc)))
	})
	return file_fibonacci_proto_rawDescData
}

var file_fibonacci_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fibonacci_proto_goTypes = []any{
	(*N)(nil), // 0: N
	(*V)(nil), // 1: V
}
var file_fibonacci_proto_depIdxs = []int32{
	0, // 0: Calc.fib:input_type -> N
	1, // 1: Calc.fib:output_type -> V
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fibonacci_proto_init() }
func file_fibonacci_proto_init() {
	if File_fibonacci_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fibonacci_proto_rawDesc), len(file_fibonacci_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fibonacci_proto_goTypes,
		DependencyIndexes: file_fibonacci_proto_depIdxs,
		MessageInfos:      file_fibonacci_proto_msgTypes,
	}.Build()
	File_fibonacci_proto = out.File
	file_fibonacci_proto_goTypes = nil
	file_fibonacci_proto_depIdxs = nil
}
