# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fibonacci.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fibonacci.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66ibonacci.proto\"\x0e\n\x01N\x12\t\n\x01n\x18\x01 \x01(\x05\"\x0e\n\x01V\x12\t\n\x01v\x18\x01 \x01(\x03\x32\x15\n\x04\x43\x61lc\x12\r\n\x03\x66ib\x12\x02.N\x1a\x02.VB\x0fZ\rfibexemplo/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fibonacci_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rfibexemplo/pb'
  _globals['_N']._serialized_start=19
  _globals['_N']._serialized_end=33
  _globals['_V']._serialized_start=35
  _globals['_V']._serialized_end=49
  _globals['_CALC']._serialized_start=51
  _globals['_CALC']._serialized_end=72
# @@protoc_insertion_point(module_scope)
