spring.application.name=fila-mensagem

# ===============================
# Configurações do PostgreSQL
# ===============================

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/sd_database
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Configurações do RabbitMQ
# ===============================

spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=mqadmin
spring.rabbitmq.password=mqadmin